version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./wait-for-it.sh db:3306 -- npm run dev
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=node_be_api
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    volumes:
      - ./tmp/mysql:/var/lib/mysql
      - ./src/db:/docker-entrypoint-initdb.d